Fix: `get_path()` Methode
questionpy-org/questionpy-server pull request #125
Opened 2024-11-21 11:41 UTC by janbritz

Zuvor hat ein Aufruf von `get_path()` eines `ZipBasedPackage`-Objekts den Typ dieses Objekts zu `FastLookup` geändert.

> Note: When the source is an existing ZipFile its type (\_\_class\_\_) will be mutated to specialized type. If the caller wishes to retain original type, the caller should either create separate ZipFile object or pass a filename.

Dieser PR fügt zusätzlich noch eine `TEMPLATES_DIR`-Konstante ein.

2024-11-22 15:42 UTC, MHajoha requested changes
Was ein Crap-Verhalten seitens Python. Danke fürs Fixen :+1: 

Im SDK werden ein paar Änderungen nötig sein. Soll ich mich kümmern oder willst du?

2024-11-22 15:42 UTC, MHajoha commented on questionpy_server/worker/runtime/package.py
> +        self._zip_file = ZipFile(path)
Im SDK wird die ZIP-Seite des `ZipBasedPackage` verwendet, daher müsste das von außen zugreifbar sein

2024-11-25 09:26 UTC, janbritz commented on questionpy_server/worker/runtime/package.py
> +        self._zip_file = ZipFile(path)
Ich schau mir das SDK dazu an:)

2024-11-26 10:22 UTC, MHajoha commented on questionpy_server/worker/runtime/package.py
> +        self._zip_file = ZipFile(path)
Ich habe Desinformation verteilt

2024-11-26 10:34 UTC, MHajoha approved these changes

2024-11-27 16:58 UTC, merged