feat: `PackageCollector`
questionpy-org/questionpy-server pull request #20
Opened 2022-11-01 16:32 UTC by janbritz

Der `PackageCollector` initialisiert und managt intern folgende Sub-Kollektoren, welche das Manifest von Paketen extrahieren und eine zugehörige `Package`-Klasse erstellen:

- `LocalCollector`:
    - zuständig für alle Pakete im lokalen Ordner
    - berechnet den Hash dieser Pakete und ignoriert den Dateinamen

- `LMSCollector`:
    - zuständig für alle Pakete, welche von LMSn gesendet werden
    - diese Pakete können nur über den Hash mit `.get(hash)` beim PC abgerufen werden
    
- `RepoCollector`:
    - zuständig für alle Pakete in Repositories
    - dieser Kollektor ist noch nicht implementiert, da noch eine Repository-Struktur erarbeitet werden muss

Zusätzlich zu diesen Sub-Kollektoren wird ein `Indexer` initialisiert. Diese Klasse speichert alle `Package`s (jeglichen Ursprungs) intern ab und ermöglicht es, bei wiederholten Abfragen des selben Pakets direkt das gespeicherte `Package` zurückzugeben. Dadurch muss bei bereits indexierten Paketen nicht erneut das Manifest extrahiert werden. Nach einer vordefinierten Zeitspanne ruft der `Indexer` die `.get_packages()`-Methode des `LocalCollector`s und der `RepoCollector`en auf, um den Index zu aktualisieren.

2022-11-17 15:19 UTC, MartinGauk requested changes
Bitte schreibe auch noch ein paar mehr Kommentare. Beispielsweise zur Besonderheit des `LMSCollector`.

2022-11-17 15:19 UTC, MartinGauk commented on questionpy_server/collector/collector.py
> +        self._indexer.register_package(package, from_lms=True)
Die Pakete, die von einem LMS hochgeladen werden, dürfen nicht über die anderen Funktionen get/get_by_name/get_by_name_and_version/get_packages auffindbar sein.

2022-11-17 15:19 UTC, MartinGauk commented on questionpy_server/collector/collector.py
> +        return await self._create_package(package_hash, file)
Das `package` Objekt sollte nicht ständig neu erstellt werden, besonders weil das Beschaffen des Manifests relativ aufwändig ist.

2022-11-17 15:19 UTC, MartinGauk commented on questionpy_server/collector/collector.py
> +        return packages
Das ist inkonsistent, wenn im Ordner nachträglich noch eine neue Datei hinzugefügt wurde. (`self._map` enthält die neue Datei nicht). Es sollten zudem beim Aufruf dieser Funktion nicht immer neue `package` Objekte erstellt werden müssen.

2022-11-21 12:25 UTC, MHajoha requested changes
Ich fände hier auch noch etwas mehr Doku wichtig. Zum Beispiel ist bei Indexer nicht klar, wo sich `(un)register_package` und `update` abgrenzen, d.h. welche Fälle sie jeweils abdecken.

2022-11-21 12:25 UTC, MHajoha commented on questionpy_server/collector/abc.py
> +            return await worker.get_manifest()
Ist es wirklich nötig, einen Worker zu starten, um das Manifest zu lesen? Für das Lesen des Manifests muss doch kein Code des Pakets ausgeführt werden, sondern nur eine JSON-Datei daraus gelesen werden.

2022-11-21 12:25 UTC, MHajoha commented on questionpy_server/collector/indexer.py
> +                self.register_packages(collector_packages)
Ich glaube mindestens hier braucht es Locking. Bei `await collector.get_packages()` kann zu einer anderen Coroutine gewechselt und potenziell der aktuell leere Index abgefragt werden.

2022-11-21 12:25 UTC, MHajoha commented on questionpy_server/collector/abc.py
> +        self._cache = cache
Diesem Konstruktor könnte man ohne `worker_pool` aufrufen, was in `BaseCollector` aber einen Fehler wirft. Das muss, denke ich, nicht so generisch sein.
```suggestion
    def __init__(self, cache: FileLimitLRU, worker_pool: WorkerPool):
        super().__init__(worker_pool)
        self._cache = cache
```

Dann können wir uns auch den trivialen Konstruktor von LMSCollector sparen

2022-11-21 12:25 UTC, MHajoha commented on questionpy_server/collector/abc.py
> +        self._worker_pool = worker_pool
Wofür hier die `*args` und `**kwargs`?

2022-11-21 12:25 UTC, MHajoha commented on questionpy_server/collector/abc.py
> +        raise NotImplementedError
Es scheint ja so, als sollten die Methoden `FileNotFoundError`s werfen, wenn sie das Paket nicht kennen. Könntest du das (und etwaige andere erwartete exceptions) noch dokumentieren? Oder auch hier stattdessen None zurückgeben, das wäre konsistent mit dem `Indexer`

2022-11-21 12:25 UTC, MHajoha commented on questionpy_server/collector/collector.py
> +        self._cache.on_remove = self._indexer.unregister_package
`RepoCollector` ist zwar noch nicht implementiert, aber ich spreche es trotzdem schonmal an: Wenn ein Paket, dass es im Repo gibt, aus dem Cache evicted wird, dann würde dieses auch bis zum nächsten regelmäßigen Update aus dem Indexer fliegen. Wenn ich den Indexer richtig verstehe, soll er aber jeweils alle verfügbaren Pakete listen, oder?

2022-12-01 15:17 UTC, merged