Frage(-State) aus Form-Daten erstellen
questionpy-org/questionpy-server pull request #37
Opened 2023-01-25 18:06 UTC by MHajoha

2023-02-02 12:10 UTC, janbritz requested changes

2023-02-02 12:10 UTC, janbritz commented on questionpy_server/api/models.py
> +    question_state: str
Hier sollten wir auch die `qppe.yaml` anpassen - an jeder Stelle wird `format: json` angegeben.

2023-02-02 12:10 UTC, janbritz commented on questionpy_server/api/routes.py
> +    async with qpyserver.worker_pool.get_worker(package_path, 0, None) as worker:
Statt `None`, kann eigentlich direkt `data.context` übergeben werden (obwohl er ja eigentlich aktuell sowieso ignoriert wird).

2023-02-02 12:10 UTC, janbritz commented on questionpy_server/worker/runtime/lib.py
> +from .messages import WorkerError
Das war bestimmt keine Absicht? :smile:

2023-02-02 12:10 UTC, janbritz commented on questionpy_server/api/routes.py
> +        new_state = await worker.create_question_from_options(question_state, data.form_data)
Ich denke, hier müsste der `question_state` ggf. erst gelesen werden, da es vom Typ `Optional[Path]` ist und `worker.create_question_from_options()` `Optional[bytes]` erwartet.

2023-02-02 12:10 UTC, janbritz commented on questionpy_server/api/models.py
> +class QuestionCreateArguments(OptionalQuestionStateHash):
Am besten Übernehmen wir die Änderung direkt auch in der [qppe.yaml](https://github.com/questionpy-org/questionpy-server/blob/dev/docs/qppe.yaml#L510-L518).

2023-02-08 15:56 UTC, MartinGauk approved these changes

2023-02-08 15:57 UTC, merged