#42: ThreadWorker
questionpy-org/questionpy-server pull request #43
Opened 2023-02-17 21:54 UTC by MHajoha

2023-03-09 16:15 UTC, MartinGauk requested changes

2023-03-09 16:15 UTC, MartinGauk commented on questionpy_server/api/routes.py
> +        response = await worker.send_and_wait_response(GetOptionsFormDefinition(), GetOptionsFormDefinition.Response)
Mir gefällt es nicht so, dass man sich mit den Messages befassen muss. Besonders für das SDK sind das unnötige Details und dann ist es besser, wenn es ein klares Interface gibt, um auf ein Paket/Worker zugreifen zu können.

2023-03-09 16:15 UTC, MartinGauk commented on questionpy_server/utils/streams.py
> +                written += self._transmit.write(data[written:])
Du könntest hier `memoryview` benutzen, damit die Daten nicht kopiert werden müssen.

Bei `read` könnte `memoryview` ebenfalls einen Kopiervorgang einsparen, falls `readinto` bei Pipes verfügbar ist.

2023-03-09 16:15 UTC, MartinGauk commented on questionpy_server/worker/connection.py
> +class ServerToWorkerConnection(AsyncIterator[MessageToServer]):
Pylint meckert über die Code-Ähnlichkeit von `ServerToWorkerConnection` und `WorkerToServerConnection`. Ich denke, dass wir das schon so belassen können, aber wir sollten die Meldung unterdrücken.

2023-03-09 16:15 UTC, MartinGauk commented on questionpy_server/worker/pool.py
> +        :param worker_type: worker implementation
Diese Zeile müsste oben stehen.

2023-03-09 17:47 UTC, MHajoha commented on questionpy_server/api/routes.py
> +        response = await worker.send_and_wait_response(GetOptionsFormDefinition(), GetOptionsFormDefinition.Response)
Ich habe die Worker-Methoden get_manifest, get_options_form_definition und create_question_from_options wieder hinzugefügt

2023-03-13 10:53 UTC, MHajoha commented on questionpy_server/utils/streams.py
> +                written += self._transmit.write(data[written:])
Sorgt `data[written:]` im Ernst dafür dass die Daten kopiert werden? :laughing: Ich hatte naiv erwartet, dass im Hintergrund einfach `&data + written` passiert. Aber okay, also `memoryview`.

2023-03-13 12:06 UTC, MHajoha commented on questionpy_server/utils/streams.py
> +                written += self._transmit.write(data[written:])
Wegen des reads: Ich hatte mich auf die Type Hints in IDEA verlassen, nach denen die streams `typing.BytesIO` sind. Anscheinend kann ich mich aber darauf verlassen, dass sie `(BufferedReader, FileIO)` sind. 

`BufferedReader.read` macht schon das, was ich da gebaut habe (blockt also bis `size` bytes da sind oder EOF da ist), `read` wird also ein one-liner.

Für `write` passt Buffering natürlich nicht. Da könnte ich höchstens `write() + flush()` benutzen, sehe ich aber nicht so recht.

2023-03-13 13:27 UTC, MHajoha commented on questionpy_server/worker/connection.py
> +class ServerToWorkerConnection(AsyncIterator[MessageToServer]):
Ich wüsste auch nicht, wie man die beiden vereinen könnte, wo sie ja eigentlich das gleiche machen. [Nur die Farbe ist anders](https://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/). Habe die Warnung ausgemacht

2023-03-16 15:22 UTC, MartinGauk approved these changes

2023-03-16 15:25 UTC, merged