Form-Daten aus State generieren
questionpy-org/questionpy-server pull request #45
Opened 2023-03-15 15:49 UTC by MHajoha

Dieser PR basiert auf #43, der davor gemergt werden muss.
* `get_options_form` erhält jetzt den Question State und gibt nicht nur die `OptionsFormDefinition` zurück, sondern auch die Form-Daten als `dict` für diese Form.
* Der Question State ist jetzt wie besprochen ein `dict[str, object]`. Ich denke dass dafür dann keine Caching-Logik mehr nötig ist, wenn davon auszugehen ist, dass große Dateien nicht Teil des States sind. Das habe ich aber noch nicht angegangen. In der Rest-API ist der State noch ein `str`.
* Ich habe ein kleines Skript geschrieben, dass die beiden Test-Pakete ezpz neu generiert. Macht aber die Annahmen, dass die SDK unter `../questionpy-sdk` und dessen Venv in `.venv` liegt.

Der questionpy-common PR dazu: https://github.com/questionpy-org/questionpy-common/pull/11

Closes #44

2023-03-17 15:31 UTC, MartinGauk reviewed
> Ich denke dass dafür dann keine Caching-Logik mehr nötig ist, wenn davon auszugehen ist, dass große Dateien nicht Teil des States sind. Das habe ich aber noch nicht angegangen. In der Rest-API ist der State noch ein str.

Ich halte das Caching schon noch für sinnvoll. In jedem Fall geht es mir darum, dass wir die Fragen im Worker im Speicher lassen können, damit der Worker und das `Question` Objekt (referenziert über den `question_state_hash`) weiter genutzt werden kann.
Aus Server-Sicht sollten wir es auch weiterhin als arbitrary str/bytes betrachten, da dort nichts drinsteht, was den Server interessieren könnte.

2023-03-17 15:31 UTC, MartinGauk commented on questionpy_server/api/routes.py
> +            state_data = json.load(state_file)
Der Server verarbeitet die Daten des question_state ja nicht weiter. Wir können es uns also sparen, das JSON zu parsen, nur um die Datenstruktur am Ende wieder zu einem JSON machen zu müssen, um es zum Worker zu schicken.
Es reicht ja aus, wenn du zunächst nur einen Pfad zu der Datei zum Worker schickst.

2023-03-20 09:26 UTC, MartinGauk commented
Ich habe jetzt noch etwas nachgedacht. Die Verwendung des question_states als String an manchen Stellen ist etwas inkonsequent, denn das Hashen eines (Unicode) Strings ist ja nicht unbedingt so einfach. Durch Normalisierung könnte man Probleme verhindern, ist aber nicht so schön.

Möglichkeiten:

1. Wir könnten weiterhin sagen, dass der question_state ein JSON sein soll, Server und Moodle-Plugin betrachten es aber als arbitrary binary data, d.h. dass wir manchmal ggf. die Daten base64 encoden müssen. Auf diese Weise ist klar, wie jederzeit der Hash gebildet werden kann. Der Overhead von 33% bei base64 ist hinnehmbar, da wir den state nicht immer mitschicken.

2. Wir hashen den question_state nicht, sondern der Server gibt dem Plugin nur eine Art cache key zurück (was trotzdem ein Hash sein kann). Der Unterschied ist, dass wir es nicht als Fehler betrachten, wenn ein Hash nicht mehr übereinstimmt.

Wir können am Mittwoch näher darüber reden, das ist zunächst nicht so relevant.

2023-03-28 10:11 UTC, MHajoha commented
Die zentrale Frage was den State angeht ist mMn: "Sollen große Date(ie)n, insbesondere BLOBs, Teil des States sein?"

Ich würde diese Frage mit "Nein" beantworten, da diese Dateien sicherlich nicht immer gebraucht werden. Zwei Beispiele:
* Studi lädt eine Abgabe (Sei es PDF oder Quellcode) hoch. Für die 20 Mal, die sie die Seite neu lädt um sicherzustellen, dass sie auch wirklich auf "Hochladen" gedrückt hat, sind maximal Metadaten der Datei relevant. Gleiches gilt für das Nachträgliche Ansehen/Überprüfen. Nur bei der Bewertung ist der Inhalt relevant. Und auch dann wird er aller Wahrscheinlichkeit nach nur einmal heruntergeladen werden müssen.
* Beim Bearbeiten der Frage werden Assets hochgeladen (z.B. Vorlagen). Diese kann sich der Studi beim Attempt herunterladen / werden angezeigt. Für das Paket und den QuestionPy-Server sind maximal die Metadaten relevant es reicht, wenn das LMS die Datei dem Client bereitstellt.

Wenn der State keine großen Daten enthält, muss er mMn auch nicht gecacht werden. Angesichts der Komplexität und ~doppelten Round-Trip-Zeiten bei Misses sollten wir das auch nicht.

2023-04-14 07:30 UTC, alexanderschmitz requested changes

2023-04-14 07:30 UTC, alexanderschmitz commented on questionpy_server/api/routes.py
> +    return json_response(data=QuestionEditFormResponse(definition=definition, form_data=form_data))
In der` qppe.yaml` sollte das auch noch angepasst werden. Ich glaube da fehlt sogar ein entsprechendes `Component`, was die `QuestionEditFormResponse` abbildet.

2023-04-14 10:11 UTC, janbritz approved these changes

2023-04-17 12:42 UTC, alexanderschmitz approved these changes

2023-04-17 15:12 UTC, MartinGauk commented on docs/qppe.yaml
> +                    additionalProperties: true
Bitte erkläre in einer description genauer, wie die Daten aussehen. Externe sollen in der Lage sein, unter Kenntnis der QPPE ihr LMS an den questionpy-server anbinden zu können.
Bei der Gelegenheit könntest du auch die Struktur von `QuestionCreateArguments.form_data` beschreiben (dieselbe Struktur wie hier?).

2023-04-17 17:05 UTC, MHajoha commented on docs/qppe.yaml
> +                    additionalProperties: true
Ich habe das in ein Component `#/components/schemas/FormData` gesetzt, mit Beschreibung und Beispiel. Beide stellen verwenden das jetzt.

2023-04-18 12:46 UTC, MartinGauk approved these changes

2023-04-18 13:40 UTC, merged