Anpassung an questionpy-common und worker-seitige stacktraces
questionpy-org/questionpy-server pull request #90
Opened 2024-02-29 18:32 UTC by MHajoha

Neben den Anpassungen für https://github.com/questionpy-org/questionpy-common/pull/27 habe ich auch eingebaut, dass im Falle von Worker-Fehlern der Stacktrace im Worker gesammelt und beim Server mit ausgegeben wird

2024-03-06 10:23 UTC, janbritz requested changes
Sehr hilfreich!

2024-03-06 10:23 UTC, janbritz commented on questionpy_server/worker/runtime/manager.py
> +import resource
Kann nach oben, aber das sollte demnächst ja `ruff` erledigen. :)

2024-03-06 10:23 UTC, janbritz commented on questionpy_server/worker/runtime/messages.py
> +            original_stacktrace = "\n".join(traceback.format_exception(type(error), error, error.__traceback__))
`format_exception` fügt selbst schon ein `\n` ans Ende der Strings.
```suggestion
            original_stacktrace = "".join(traceback.format_exception(type(error), error, error.__traceback__))
```

2024-03-11 17:11 UTC, MartinGauk commented
Hier sind jetzt zwei Angelegenheiten vermischt. Bitte konzentriere dich in diesem PR auf die Stacktraces.
Bezüglich der Scores will ich mir noch Gedanken machen.

2024-03-12 12:39 UTC, MHajoha commented
> Hier sind jetzt zwei Angelegenheiten vermischt. Bitte konzentriere dich in diesem PR auf die Stacktraces. Bezüglich der Scores will ich mir noch Gedanken machen.

Das mit den Stacktraces habe ich jetzt in #91 verschoben (und dort @janbritz' Anmerkungen eingebaut), dieser PR ist jetzt nur noch das Gegenstück zu >https://github.com/questionpy-org/questionpy-common/pull/27>

2024-05-23 15:18 UTC, closed without merging